# Generated by Django 4.1.3 on 2022-11-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Пристрій', 'verbose_name_plural': 'Пристрої'},
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(default='Samsung', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='year',
            field=models.CharField(default='2022', max_length=20),
        ),
    ]
