# Generated by Django 4.1.3 on 2022-11-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_equipment_device_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='device',
            name='equipment',
        ),
        migrations.AddField(
            model_name='device',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
