# Generated by Django 4.1.3 on 2022-12-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_equipment_remove_device_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.CharField(default='100$', max_length=100),
        ),
    ]
