# Generated by Django 4.1.3 on 2022-12-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_device_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='link',
            field=models.TextField(default='/'),
        ),
        migrations.AlterField(
            model_name='device',
            name='text',
            field=models.TextField(),
        ),
    ]
