# Generated by Django 4.1.3 on 2022-12-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_device_link_alter_device_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type_device',
            field=models.CharField(default='Смартфон', max_length=255),
        ),
    ]
